version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 16
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - postgres
      - redis

    volumes:
      - ..:/workspace:cached

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-extensions.sql:/docker-entrypoint-initdb.d/create-extensions.sql
    environment:
      POSTGRES_PASSWORD: quicksend
      POSTGRES_USER: quicksend
      POSTGRES_DB: quicksend

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    networks:
      - redis
    volumes:
      - redis-data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=quicksend

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Redis locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
  redis-data:

networks:
  postgres:
  redis:
