# Replace all values of "CHANGE_THIS" to actual values

database:
  hostname: "localhost"
  name: "quicksend"
  password: "CHANGE_THIS"
  port: 5432
  username: "CHANGE_THIS"

domains:
  backend: "CHANGE_THIS"
  frontend: "CHANGE_THIS"

env: "production"

port: 3000

redis:
  hostname: "localhost"
  port: 6379

secrets:
  applications: "CHANGE_THIS"
  recaptcha: "CHANGE_THIS"
  sessions: "CHANGE_THIS"

smtp:
  from: "CHANGE_THIS"
  host: "CHANGE_THIS"
  password: "CHANGE_THIS"
  port: 465
  secure: true
  tls: true
  username: "CHANGE_THIS"

storage:
  engine: "disk"
  limits:
    files: 5
    fileSize: 10000000
  options:
    directory: "/uploads"

throttler:
  limit: 250
  ttl: 60
